### ISSUE TITLE
support for python 3.6

### ISSUE THREAD

**Issue by floriankrb** [pytroll/pyresample#100]
The README.md file (https://github.com/pytroll/pyresample/blob/master/README.md) states that 
"Pyresample is tested with Python 2.6, 2.7, 3.2, 3.3, and 3.4."

Is there any known limitations with python 3.6 ?
Should the README.md file be updated ?

**Comment by davidh-ssec** [comment]
Not that we know of. Just an old README. As you can see we are testing it with 3.4-3.6 on travis: https://travis-ci.org/pytroll/pyresample

**Comment by floriankrb** [comment]
Thanks for the quick response !
