### ISSUE TITLE
Bilinear interpolation leaves holes in fields with constant value

### ISSUE THREAD

**Issue by pnuu** [pytroll/pyresample#111]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
import numpy as np
import matplotlib.pyplot as plt
from pyresample import geometry, image
from satpy.resample import get_area_def

# Built-in area definition from SatPy
AREA_DEF = get_area_def('scan')

in_shape = (100, 100)
# These coordinates exceed the extent of target area
lons, lats = np.meshgrid(np.linspace(-25., 40., num=in_shape[0]), np.linspace(45., 75., num=in_shape[1]))
data = np.ones((in_shape[0], in_shape[1]))
swath_def = geometry.SwathDefinition(lons=lons, lats=lats)
# Bilinear
swath_con_bil = image.ImageContainerBilinear(data, swath_def, 50000, fill_value=None)
area_con_bil = swath_con_bil.resample(AREA_DEF)
# Nearest neighbour
swath_con_nearest = image.ImageContainerNearest(data, swath_def, 50000, fill_value=None)
area_con_nearest = swath_con_nearest.resample(AREA_DEF)

# Zero masked pixels, as is correct
print area_con_nearest.image_data.mask.sum()
# And all values are 1.0
print np.all(area_con_nearest.image_data == 1.0)

# With bilinear, plenty of masked pixels (28505)
print area_con_bil.image_data.mask.sum()
# The corresponding pixels are also set to NaN (prints 28505)
print np.isnan(area_con_bil.image_data.data).sum()
```
#### Problem description
When resampling a constant-valued dataset using bilinear interpolation there are missing values in the resulting data, even if the data has no missing values. In my case the dataset is IASI pressure data from upper atmosphere.

#### Expected Output
Constant value data for the whole target area covered by the used dataset. Boundary effects are ok, but there should not be holes.

#### Actual Result, Traceback if applicable
There are holes in the data, see the image.

![bilinear_holes](https://user-images.githubusercontent.com/3170788/39043633-9577ba00-4496-11e8-85c8-b3729092ea60.png)

#### Versions of Python, package at hand and relevant dependencies
Python 2.7.12, current PyResample master branch (and develop)

**Comment by pnuu** [comment]
Ok, the problem is when bilinear interpolation gets out of the original range of the data:

https://github.com/pytroll/pyresample/blob/master/pyresample/bilinear/__init__.py#L162

Will fix at the latest during the PyTroll Workshop next week.

**Comment by davidh-ssec** [comment]
Sounds good. I will try to finish my cartopy PR and we can make a release with these two updates.
