### ISSUE TITLE
check usage of GridDefinition and longitude wrapping

### ISSUE THREAD

**Issue by mraspaud** [pytroll/pyresample#14]
_From [lavergne...@gmail.com](https://code.google.com/u/110388910077036912843/) on December 11, 2013 09:48:59_

Check http://earthpy.org/interpolation_between_grids_with_pyresample.html 1. it was necessary to use SwathDefinition for orig_def and targ_def while I would have expected to use GridDefinition (using GridDefinition instead of SwathDefinition breaks the resampled field).
1. I had to substract 180 to the NCEP longitude (or the resampled was broken). That is not intuitive since exerything should happen in cartesian space.

Thomas

_Original issue: http://code.google.com/p/pyresample/issues/detail?id=14_

**Comment by mraspaud** [comment]
What's the status on this @TomLav ?

**Comment by TomLav** [comment]
I think this is closed: https://github.com/pytroll/pyresample/commit/42950a0c5ac45623ca113c7864dd7346f5b69cdb

**Comment by mraspaud** [comment]
@TomLav ok, closing then, feel free to reopen if needed
