### ISSUE TITLE
No coastlines in cartopy if area is flipped

### ISSUE THREAD

**Issue by sfinkens** [pytroll/pyresample#160]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
import pyresample.geometry
import matplotlib.pyplot as plt
from satpy.readers.utils import get_geostationary_mask

proj_dict = {'proj': 'geos', 'lon_0': 0.0, 'a': 6378169.00, 'b': 6356583.80,
             'h': 35785831.00, 'units': 'm'}

extents = {
    'flipped': (5500000, 5500000, -5500000, -5500000),  # (SEVIRI like)
    'north up': (-5500000, -5500000, 5500000, 5500000)
}

for desc, extent in extents.items():
    area_def = pyresample.geometry.AreaDefinition(
        proj_id='geos',
        description='Full Disk',
        area_id='full-disk',
        projection=proj_dict,
        width=100, height=100,
        area_extent=extent
    )

    crs = area_def.to_cartopy_crs()
    fig, ax = plt.subplots(subplot_kw={'projection': crs})
    ax.coastlines()
    ax.imshow(get_geostationary_mask(area_def), transform=crs, extent=crs.bounds, origin='upper')
    ax.set_title(desc)

plt.show()

```
#### Problem description
If an ``AreaDefinition`` is flipped N-S and E-W, i.e. South is up and East is left, cartopy fails to draw coastlines for the crs returned by ``AreaDefinition.to_cartopy_crs()``.

#### Expected Output
![flipped_correct](https://user-images.githubusercontent.com/1991007/52720514-0a941980-2fa8-11e9-831c-1fe57aee66b2.png)

#### Actual Result, Traceback if applicable
![flilpped](https://user-images.githubusercontent.com/1991007/52720521-0e27a080-2fa8-11e9-9192-18dbc0d72dcd.png)

#### Versions of Python, package at hand and relevant dependencies
pyresample 1.10.3+152.g5dbfcc4.dirty
cartopy 0.17.1.dev146+

**Comment by djhoese** [comment]
I personally think this is something that shouldn't work, but given that your solution is so simple I guess I'm ok with it. I'll have to see if I need to update my cartopy PR that also implements these classes.

**Comment by sfinkens** [comment]
I'm glad it works because the satpy ``seviri_l1b_hrit`` reader returns scenes with such flipped area definitions :)
