### ISSUE TITLE
Missing metadata on PyPI

### ISSUE THREAD

**Issue by QuLogic** [pytroll/pyresample#172]
This package [on PyPI](https://pypi.org/project/pyresample/) appears to be missing some metadata. It does not have a long description, or a homepage link to here/the docs. The summary is "Resampling of remote sensing data in Python", which seems outdated as the tagline here on GitHub is "Geospatial image resampling in Python" now.

**Comment by djhoese** [comment]
So we need to add the `long_description` to the setup.py. I can do this tomorrow if you don't get to it today (it's 5pm on a Friday here, I'd like to get offline at some point).

**Comment by djhoese** [comment]
Closed by #173
