### ISSUE TITLE
Unit test fail in test_swath for test_self_map and test_self_map_multi

### ISSUE THREAD

**Issue by cdeil** [pytroll/pyresample#22]
I see two unit test fails from pyresample on Mac OS X 10.10 with numpy 1.9.1:
- Python 2: https://gist.github.com/cdeil/f89d37a9314d518228a8
- Python 3: https://gist.github.com/cdeil/c0767a434fafbe7a04d0

I think the fail is the same, but for some reason only on Python the values are printed by nose!???

```
======================================================================
FAIL: test_self_map (pyresample.test.test_swath.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/deil/code/pyresample/pyresample/test/test_swath.py", line 51, in test_self_map
    msg='Failed self mapping swath for 1 channel')
AssertionError: 668848.14481726696 != 668848.082208 within 1 places : Failed self mapping swath for 1 channel

======================================================================
FAIL: test_self_map_multi (pyresample.test.test_swath.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/deil/code/pyresample/pyresample/test/test_swath.py", line 71, in test_self_map_multi
    msg='Failed self mapping swath multi for channel 1')
AssertionError: 668848.14481726696 != 668848.082208 within 1 places : Failed self mapping swath multi for channel 1

----------------------------------------------------------------------
```

There's also a bunch of warnings that I guess should be caught in the library or tests if it's normal and expected behaviour.

**Comment by mraspaud** [comment]
Thanks for reporting this @cdiel !
Unfortunately we have no access to macos machines here, and travis-ci doesn't seem to be wanting to run on osx at the moment, so it's a bit hard to debug. Do you have a possibility patch this and send a pull request ? Thanks !

**Comment by mraspaud** [comment]
@davidh-ssec @cdeil Are the unittests working in MacOS now ?

**Comment by davidh-ssec** [comment]
@mraspaud Yes they should now with commits 6a035f380668ee0541455fd6e501e88a05382f0f and ac6132cba963d5b400bddbeb2590d3bd5314d404.
