### ISSUE TITLE
Area definition boundaries where space pixels are excluded

### ISSUE THREAD

**Issue by pnuu** [pytroll/pyresample#228]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
from pyresample.boundary import AreaDefBoundary
from satpy.resample import get_area_def

adp = AreaDefBoundary(get_area_def('euro4'))
print(adp.sides_lats[0].min(), adp.sides_lats[0].max())
adp = AreaDefBoundary(get_area_def('met09globeFull'))
print(adp.sides_lats[0].min(), adp.sides_lats[0].max())
```
prints
```python
60.951524071578824 75.894364937051
1e+30 1e+30
```

#### Problem description

The above example is technically what is expected; the boundary of an area definition is retrieved. In the case of `geos` projection of the latter example all the edges are in space.

For sunlight coverage calculations (see https://github.com/pytroll/trollflow2/pull/67) this always results in coverage of 100 %.

Is there a (computationally cheap) method that could compute the boundary in such a way that the invalid (space) regions would be excluded and the boundary would follow the edge of Earth instead? Or other ways to get around this sunlight coverage problem in these cases?

**Comment by mraspaud** [comment]
For geostationary, there are a couple of function to mask out the space pixels somewhere, and one of these is computing a polygon around the globe, maybe it can help ?

**Comment by pnuu** [comment]
Interesting, I'll have a look at those functions.

**Comment by pnuu** [comment]
Found it: `satpy.readers.utils.get_geostationary_bounding_box()`. With a quick glance this is exactly what is needed.

**Comment by pnuu** [comment]
I implemented this to trollflow2 (https://github.com/pytroll/trollflow2/pull/67) for now. The feature should be moved from Satpy to Pyresample at a later time.

**Comment by djhoese** [comment]
@pnuu PCW task?

**Comment by pnuu** [comment]
Yeah, I thought that I'd have a look at this there, but already finished :grin: Blame @mraspaud to point me to the right direction. I'll remove the card.

**Comment by pnuu** [comment]
Oh, right. For the Satpy -> Pyresample transition. Sure!
