### ISSUE TITLE
Release wheels for pyresample

### ISSUE THREAD

**Issue by djhoese** [pytroll/pyresample#244]
Right now we only release sdist tarballs for pyresample. There are C extensions as part of pyresample and by not releasing wheels we make users have to have C compilers on their machines when they install pyresample from PyPI.

Adding wheel generation can be difficult, but I've handled it in some other projects. The best version is probably in vispy: https://github.com/vispy/vispy/blob/master/azure-pipelines.yml

Someone in the past (@astrofrog maybe?) pointed me to a project where all of this logic was trying to be shared between projects (setting up azure and building wheels) but I can't find it now.

**Comment by astrofrog** [comment]
Here are the templates I mentioned before:

https://github.com/OpenAstronomy/azure-pipelines-templates/

Just to be clear they are not astronomy-specific. See the README for details.
