### ISSUE TITLE
AreaDefinition docstring does not agree with its constructors definition

### ISSUE THREAD

**Issue by gerritholl** [pytroll/pyresample#261]
#### Code Sample, a minimal, complete, and verifiable piece of code

In the interactive ipython console:

```python
import pyresample
help(pyresample.AreaDefinition)
```
#### Problem description

There is a discrepancy between the signature of the `AreaDefinition` and the order of the parameters in the documentation.

The signature has mandatory arguments `area_id`, `description`, `proj_id`, `projection`, `width`, `height`, `area_extent`, and optional arguments `rotation`, `nprocs`, `lons`, `lats`, and `dtype`.

The docstring has arguments `area_id`, `description`, `proj_id`, `projection`, `width`, `height`, `rotation`, `area_extent`, `nprocs`.

The `rotation` parameter is out of order in the docstring, it has swapped with `area_extent` compared to the real case.

It also doesn't state that `rotation` is optional.

```
pyresample.AreaDefinition(
    area_id,
    description,
    proj_id,
    projection,
    width,
    height,
    area_extent,
    rotation=None,
    nprocs=1,
    lons=None,
    lats=None,
    dtype=<class 'numpy.float64'>,
)
Docstring:
Holds definition of an area.

Parameters
----------
area_id : str
    Identifier for the area
description : str
    Human-readable description of the area
proj_id : str
    ID of projection
projection: dict or str
    Dictionary or string of Proj.4 parameters
width : int
    x dimension in number of pixels, aka number of grid columns
height : int
    y dimension in number of pixels, aka number of grid rows
rotation: float
    rotation in degrees (negative is cw)
area_extent : list
    Area extent as a list (lower_left_x, lower_left_y, upper_right_x, upper_right_y)
nprocs : int, optional
    Number of processor cores to be used for certain calculations
```
#### Expected Output

I would expect the docstring to describe the parameters in the order in which they are required by `__init__` and all optional arguments to be described as such.

#### Actual Result, Traceback if applicable

The actual documented order is inconsistent with the definition, see above for details.

#### Versions of Python, package at hand and relevant dependencies

Pyresample `1.14.0+19.gc28b6f6.dirty`.

**Comment by djhoese** [comment]
Agreed. Would you mind make a pull request to fix it?
