### ISSUE TITLE
`kd_tree.get_sample_from_neighbour_info` can't handle `fill_value` with `numpy` data types.

### ISSUE THREAD

**Issue by owenlittlejohns** [pytroll/pyresample#272]
#### Problem description

We're using `pyresample` to interpolate satellite data that can have a variety of data types. Some of these data include types such as unsigned 8-bit integers, available through `numpy` (e.g. `numpy.uint8`). `numpy` arrays of these data types work fine with nearest neighbour interpolation if we don't specify a fill value.

We hit a `TypeError` in `get_sample_from_neighbour_info` if we use a `fill_value` with a `numpy` data type. (We have a work around to cast numpy types to `int` or `float` before interpolation but that seems a bit inelegant).

Looking at [kd_tree.py](https://github.com/pytroll/pyresample/blob/master/pyresample/kd_tree.py#L681), a possible tweak to the relevant `isinstance` expression could be to add the `numpy.floating` and `np.integer` types, which encapsulate all the various `numpy` float and integer types. I'd be happy to work on that and make pull request.

#### Code Sample:

Current condition checking type of `fill_value` (kd_tree.py, L681):

```python
if not isinstance(fill_value, (long, int, float)) and fill_value is not None:
        raise TypeError('fill_value must be number or None')
```

Proposed change:

```python
if not isinstance(fill_value, (long, int, float, np.integer, np.floating)) and fill_value is not None:
    raise TypeError('fill_value must be number or None')
```

#### Expected Output

The `fill_value` keyword argument should be considered valid for numerical `numpy` data types.

#### Actual Result, Traceback if applicable

Raises the `TypeError` from snippet above.

#### Versions of Python, package at hand and relevant dependencies

Python 3.7.7
Conda
Docker

---

P.S. This package has proven really handy - using it to decompose interpolation into two steps, and not have to re-run the first step getting thing like the neighbour information has significantly improved our performance! Thanks!

**Comment by djhoese** [comment]
Thanks for dealing with this and finding a solution. Nice job.

I'm wondering if that `if` statement should just be removed. It seems very unpythonic to require a certain type of something. That said, it does provide a better error message for the user than what numpy will probably show it down the road it fails. @mraspaud @pnuu thoughts?

**Comment by mraspaud** [comment]
Thanks for debugging this! 
I'd be ok with removing this test altogether. On lines 732 and 840 we end up assigning `fill_value` to some of the elements of the array, which will fail if the type doesn't match, like this:
```python
arr = np.arange(4, dtype=np.uint8)                                                                                                                                                                                                                                                 
arr[1] = 'hej'   
```
```python-traceback                                                                                                                                                                                                                                                                  
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-f2772042ef36> in <module>
----> 1 arr[1] = 'hej'

ValueError: invalid literal for int() with base 10: 'hej'
```
I believe this is good enough.

@owenlittlejohns Would you be willing to create a PR for this ? and I'm happy to hear pyresample has proven useful !

**Comment by owenlittlejohns** [comment]
Sounds great. I'll work up a PR! Thanks for the quick response, both.
