### ISSUE TITLE
Add Elliptical Weighted Nearest Neighbor option for swath resampling

### ISSUE THREAD

**Issue by D-Auty** [pytroll/pyresample#293]
An Elliptical Weighted Nearest Neighbor (EWNN) option would be a derivative of the Elliptical Weighted Average (EWA) implementation.  Whereas the EWA algorithm does a weighted average of the neighboring cells, using a forward resampling technique, EWNN would use the same setup but only choose the “closest” or highest weighting of the neighboring cells.  Such an option would be as performant or better than EWA, and faster than the basic KD-Tree nearest-neighbor option.  Also, such an option would avoid some of the resampling artifacts that are present in the KD-Tree option.

There is a related issue that could be written against the KD-Tree option - the appearance of edge “finger” or “fringe” artifacts that extend beyond the base perimeter of the input data.  An EWNN option would be faster than the KD-Tree option and avoid these resampling artifacts.

We (Data Services team, Data-Use Release Train, ESDIS Support, NASA/Goddard) would like to contribute to the development of this feature, assuming it does not conflict with other development activity.

**Comment by mraspaud** [comment]
@D-Auty, thanks for opening this issue, EWNN would be a great addition indeed! EW takes advantage of the geometry of the scanning and would indeed be faster than kd-tree when available.

I'll let @djhoese give the last word here, as he is actively working on the EWA algorithm at the moment and has been the maintainer of it, but I'm all in favour.

**Comment by djhoese** [comment]
There is an existing `maximum_weight_mode` boolean flag (defaults to False) that should perform the equivalent behavior. It will only take the input pixel that has the maximum weight of all the pixels that intersect the output grid cell. Try passing `maximum_weight_mode=True` to the existing EWA resampling and check it out. I already use this for category products in some of my work where taking the average of categories (ex. 0=clear sky, 1=probably clear, 2=partly cloudy, 3=cloudy)doesn't make sense.

**Comment by D-Auty** [comment]
Quite the news flash.  I will definitely check this out and report back.  Maybe this is easier than first thought ;-)

**Comment by djhoese** [comment]
As mentioned above `maximum_weight_mode` should perform the desired effect. Feel free to comment if you've found otherwise and we can reopen.
