### ISSUE TITLE
Add CITATION information

### ISSUE THREAD

**Issue by djhoese** [pytroll/pyresample#296]
People using pyresample may want to cite it. As far as I know we don't point out how to do that anywhere. Satpy has a CITATION document that we could mimic here in pyresample but have it point to the pyresample zenodo page.

https://github.com/pytroll/satpy/blob/master/CITATION

https://zenodo.org/record/3888692#.Xz1Dlhl7mV4

We could also add the DOI badge (see right pane of zenodo page) to the README.

And lastly a sentence or two (maybe a separate section) should probably be added to the home page of the sphinx documentation (docs/source/index.rst).

**Comment by cgentemann** [comment]
https://github.com/pytroll/pyresample/pull/314
