### ISSUE TITLE
Comparison of AreaDefinition to other types fails

### ISSUE THREAD

**Issue by jleinonen** [pytroll/pyresample#315]
Comparing an AreaDefinition to an object of incompatible type such as `None` seems to cause an error.

#### Code Sample, a minimal, complete, and verifiable piece of code

```python
# Your code here
from pyresample import AreaDefinition

# create some areas for testing
area1 = AreaDefinition(**{
    "description": "test_area_1",
    "proj_id": "latlong",
    "projection": {"proj": "latlong"},
    "width": 10,
    "height": 10,
    "area_id": "test_area_1",
    "area_extent": (5.0, 45.0, 15.0, 55.0)
})
area2 = AreaDefinition(**{
    "description": "test_area_2",
    "proj_id": "latlong",
    "projection": {"proj": "latlong"},
    "width": 10,
    "height": 10,
    "area_id": "test_area_2",
    "area_extent": (0.0, 45.0, 10.0, 55.0)
})

print(area1 == area2) # False
print(area1 == area1) # True
print(area1 == None) # raises an exception
```
#### Problem description

I encountered this issue when I was using `None` as a placeholder for an `AreaDefinition` that has not yet been initialized. With the current behavior you have to separately test for `area1 is None`  before running the comparison.

This looks like an easy fix to add to the `__eq__` function.

#### Expected Output

Python objects usually return `False` rather than raising an error when tested for equality to an incompatible type.
```python
>>> 42 == None
False
```
#### Actual Result, Traceback if applicable

The last line of the example raises the following exception:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<path>/lib/python3.8/site-packages/pyresample/geometry.py in __eq__(self, other)
   1589         try:
-> 1590             return ((self.proj_str == other.proj_str) and
   1591                     (self.shape == other.shape) and

AttributeError: 'NoneType' object has no attribute 'proj_str'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-44-b1f1c34d2b6b> in <module>
----> 1 print(area1 == None)

<path>/lib/python3.8/site-packages/pyresample/geometry.py in __eq__(self, other)
   1592                     (np.allclose(self.area_extent, other.area_extent)))
   1593         except AttributeError:
-> 1594             return super(AreaDefinition, self).__eq__(other)
   1595 
   1596     def __ne__(self, other):

<path>/lib/python3.8/site-packages/pyresample/geometry.py in __eq__(self, other)
    117         if self is other:
    118             return True
--> 119         if other.lons is None or other.lats is None:
    120             other_lons, other_lats = other.get_lonlats()
    121         else:

AttributeError: 'NoneType' object has no attribute 'lons'
```

#### Versions of Python, package at hand and relevant dependencies
Python version: 3.8.6
Pyresample version: 1.16.0

**Comment by djhoese** [comment]
While I wouldn't be surprised that this fails in other cases, in Python you always want to compare `None` by doing `my_obj is None`. If you do this style of comparison (identity comparison), do you still get an error?

**Comment by djhoese** [comment]
Ah I didn't read the whole issue, I see you brought up the `is None` part. I'd be ok with an explicit check for the same dtype in the `__eq__` method.

@jleinonen Do you think you could make a pull request for this addition?

**Comment by gerritholl** [comment]
I thought I fixed this in https://github.com/pytroll/pyresample/pull/288 ...

**Comment by gerritholl** [comment]
Please upgrade to pyresample 1.17, where this bug was already fixed, see #288.  I just tried your code using current pyresample and the output is:

```
False
True
False
```

**Comment by djhoese** [comment]
Thank you @gerritholl !

**Comment by jleinonen** [comment]
Thanks, my bad for not checking the new version!
