### ISSUE TITLE
Upgrade to pyresample 1.17.0 causes IndexError with one-dimensional data

### ISSUE THREAD

**Issue by ibrewster** [pytroll/pyresample#316]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
import numpy as np
from pyresample import bilinear
from pyresample import geometry


lons = np.random.uniform(low = -180, high = -138, size = (50000, ))
lats = np.random.uniform(low = 39, high =70.46, size = (50000, ))
data = np.random.uniform(low = -10, high = 50, size = (50000,))

target_def = geometry.create_area_def('areaDef',
                                      {'proj': 'merc', 'lon_0': '-90',
                                       'preserve_units': False},
                                      shape = (191, 255),
                                      area_extent = (-13358339.0, 4766363.8393,
                                                     -5381740.7803, 11196850.9909))

source_def = geometry.SwathDefinition(lons=lons, lats=lats)

t_params, s_params, input_idxs, idx_ref = bilinear.get_bil_info(source_def, target_def, radius=5e4)
binned_data = bilinear.get_sample_from_bil_info(data,
                                                t_params, s_params, input_idxs, idx_ref,
                                                output_shape=target_def.shape)
print(binned_data)

```
#### Problem description

Under pyresample 1.16.0 and prior, the above code works as expected, producing a resampled and gridded output of the one-dimensional input data. Upon updating to pyresample 1.17.0, and making no other changes, the above code throws an IndexError.

#### Expected Output

The code should output the test data, resampled and gridded, something along the lines of:

```
[[        nan         nan         nan ...         nan         nan
          nan]
 [        nan         nan         nan ... 25.55014136 36.45013971
  37.1204479 ]
 [        nan         nan         nan ... 18.7985475  18.62705137
   3.53300644]
 ...
 [        nan         nan         nan ... 30.81469108 33.90950987
  44.16990737]
 [        nan         nan         nan ...  9.22580735 26.80354262
  28.44779028]
 [        nan         nan         nan ... 40.02361386  5.08059037
  21.4851057 ]]
```

This is, in fact, the actual output from pyresample 1.16.0. The nan values are presumably due to poor area_extent choice in the example.

#### Actual Result, Traceback if applicable
Under pyresample 1.17.0, I get the following traceback:

```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    t_params, s_params, input_idxs, idx_ref = bilinear.get_bil_info(source_def, target_def, radius=5e4)
  File "/Users/israel/Development/test_pyresample/lib/python3.7/site-packages/pyresample/bilinear/_numpy_resampler.py", line 228, in get_bil_info
    numpy_resampler.get_bil_info(kdtree_class=kdtree_class, nprocs=nprocs)
  File "/Users/israel/Development/test_pyresample/lib/python3.7/site-packages/pyresample/bilinear/_base.py", line 118, in get_bil_info
    self._get_slices()
  File "/Users/israel/Development/test_pyresample/lib/python3.7/site-packages/pyresample/bilinear/_base.py", line 186, in _get_slices
    cols, lines = np.meshgrid(np.arange(shp[1]),
IndexError: tuple index out of range
```

Note that the result is the same if I use `NumpyBilinearResampler` instead of the now-deprecated `get_bil_info` (since it still calls `numpy_resampler.get_bil_info`), however that code is not directly comparable between 1.16.0 and 1.17.0.

#### Versions of Python, package at hand and relevant dependencies
This was tested with python version 3.7.7, in a clean `venv` after running `pip install pyresample` and `pip install pyresample==1.16.0` on Mac OS X Catalina.

**Comment by pnuu** [comment]
Thanks for reporting. I can confirm this, and see why this is happening. I'll try to find a fix soon.

**Comment by pnuu** [comment]
Actually, I think I already have a fix, but was seeing different results than in the above copy paste. Random input might mean that also the output is not the same :joy:  I'll just need to come up with some tests before creating a pull request, but you can test the code from here: https://github.com/pnuu/pyresample/tree/bugfix-1d-bilinear

I haven't validated the results properly, but by checking some values it should be ok, see below.

```python
target_lons, target_lats = target_def.get_lonlats()
dists = (lons - target_lons[150, 150])**2 + (lats - target_lats[150, 150])**2
print(binned_data[149:152, 149:152])
print(data[np.argmin(dists)])
```
prints:
```python
array([[31.52854187, 48.89751373, 36.44111348],
       [32.947177  , 28.41197003, 38.52923323],
       [17.87022053, 23.04710807, 27.49406821]])
28.0825974353506
```
which seems reasonable to me.

**Comment by pnuu** [comment]
Ok, I verified that the fix works for the `NumpyBilinearResampler` using some VIIRS data read with Satpy, computed to Numpy arrays, raveled to 1D and created the `SwathDefinition` from the raveled coordinates:

![bilinear](https://user-images.githubusercontent.com/3170788/103988878-79c81780-5197-11eb-96ca-ccd1958590af.png)

The swath edges have artifacts for some reason due to the bowtie deleted pixels of the VIIRS data. The same happens with the current implementation via Satpy, so is not caused by this fix.

**Comment by djhoese** [comment]
So bilinear can't handle fill values properly then? Do we need another issue for this?

**Comment by ibrewster** [comment]
I was just curious if there had been any progress on this? I'm still stuck back on 1.16 due to it, while it looks like the current version is 1.19. I'd prefer to not fall *too* far behind, if possible :-)

**Comment by pnuu** [comment]
Unfortunately I haven't had time to work on this lately. I also have a problem with how to handle the 1D data with `XArrayBilinearResampler`, see the comment in the [linked draft](https://github.com/pytroll/pyresample/pull/324).
