### ISSUE TITLE
Fix mask_all_nan kwarg in Average Bucket Resampler

### ISSUE THREAD

**Issue by ameraner** [pytroll/pyresample#317]
```python
from pyresample import create_area_def
from pyresample.bucket import BucketResampler
import dask.array as da
import numpy as np

area = create_area_def(
    area_id='test',
    projection={'proj': 'latlong'},
    center=(0., 0.),
    width=1,
    height=1,
    resolution=10.0
)

lons = da.from_array(np.array([0, 0, 0, 0]), chunks=2)
lats = da.from_array(np.array([0, 0, 0, 0]), chunks=2)
resampler = BucketResampler(source_lats=lats,
                            source_lons=lons,
                            target_area=area)


print('No fill_value passed:')

data = da.from_array(np.array([1, 2, 3, 4]), chunks=2)
print('mask_all_nan=False, all valid values: ', resampler.get_average(data, mask_all_nan=False).compute())
print('mask_all_nan=True,  all valid values: ', resampler.get_average(data, mask_all_nan=True).compute())

data = da.from_array(np.array([1, 2, np.nan, 4]), chunks=2)
print('mask_all_nan=False, one NaN value: ', resampler.get_average(data, mask_all_nan=False).compute())
print('mask_all_nan=True,  one NaN value: ', resampler.get_average(data, mask_all_nan=True).compute())

data = da.from_array(np.array([np.nan, np.nan, np.nan, np.nan]), chunks=2)
print('mask_all_nan=False, all NaN values: ', resampler.get_average(data, mask_all_nan=False).compute())
print('mask_all_nan=True,  all NaN values: ', resampler.get_average(data, mask_all_nan=True).compute())

print('\nfill_value passed as -999:')

data = da.from_array(np.array([1, 2, 3, 4]), chunks=2)
print('mask_all_nan=False, all valid values: ', resampler.get_average(data, fill_value=-999, mask_all_nan=False).compute())
print('mask_all_nan=True,  all valid values: ', resampler.get_average(data, fill_value=-999, mask_all_nan=True).compute())

data = da.from_array(np.array([1, 2, np.nan, 4]), chunks=2)
print('mask_all_nan=False, one NaN value: ', resampler.get_average(data, fill_value=-999, mask_all_nan=False).compute())
print('mask_all_nan=True,  one NaN value: ', resampler.get_average(data, fill_value=-999, mask_all_nan=True).compute())

data = da.from_array(np.array([np.nan, np.nan, np.nan, np.nan]), chunks=2)
print('mask_all_nan=False, all NaN values: ', resampler.get_average(data, fill_value=-999, mask_all_nan=False).compute())
print('mask_all_nan=True,  all NaN values: ', resampler.get_average(data, fill_value=-999, mask_all_nan=True).compute())


```
#### Problem description
The kwarg `mask_all_nan` has no influence on the results, no matter how many NaNs are present in the data, and if the `fill_value` is set or not. As it is supposed to work now, it doesn't make much sense in my opinion anyway, since the result of the average of all-NaN can only be NaN/FillValue anyway.

I would propose to repurpose the `mask_all_nan` kwarg such that, if set `True`, the averaged bucket is NaN if at least one of the elements in the bucket is NaN. If the kwarg is `False`, the average should be computed from the valid elements (as it's done now, i.e. a `nanmean` functionality). 

Or, even better, should we get rid of the old `mask_all_nan` kwarg and introduce a new one, e.g. called `mask_if_one_nan`, for this functionality? This would probably be the most clean and transparent thing to do, I would say. Feedback appreciated :)

#### Expected Output
```bash
No fill_value passed:
mask_all_nan=False, all valid values:  [[2.5]]
mask_all_nan=True,  all valid values:  [[2.5]]
mask_all_nan=False, one NaN value:  [[2.33333333]]
mask_all_nan=True,  one NaN value:  [[nan]]
mask_all_nan=False, all NaN values:  [[nan]]
mask_all_nan=True,  all NaN values:  [[nan]]

fill_value passed as -999:
mask_all_nan=False, all valid values:  [[2.5]]
mask_all_nan=True,  all valid values:  [[2.5]]
mask_all_nan=False, one NaN value:  [[2.33333333]]
mask_all_nan=True,  one NaN value:  [[-999]]
mask_all_nan=False, all NaN values:  [[-999.]]
mask_all_nan=True,  all NaN values:  [[-999.]]
```

#### Actual Result
```bash
No fill_value passed:
mask_all_nan=False, all valid values:  [[2.5]]
mask_all_nan=True,  all valid values:  [[2.5]]
mask_all_nan=False, one NaN value:  [[2.33333333]]
mask_all_nan=True,  one NaN value:  [[2.33333333]]
mask_all_nan=False, all NaN values:  [[nan]]
mask_all_nan=True,  all NaN values:  [[nan]]

fill_value passed as -999:
mask_all_nan=False, all valid values:  [[2.5]]
mask_all_nan=True,  all valid values:  [[2.5]]
mask_all_nan=False, one NaN value:  [[2.33333333]]
mask_all_nan=True,  one NaN value:  [[2.33333333]]
mask_all_nan=False, all NaN values:  [[-999.]]
mask_all_nan=True,  all NaN values:  [[-999.]]
```

**Comment by ameraner** [comment]
@pnuu @sfinkens As discussed! Please give me your opinion on the old/new kwarg issue. Thanks!

**Comment by sfinkens** [comment]
Thanks for brining this up @ameraner ! I agree that the `mask_all_nan` kwarg is not necessary here. The average is essentially implemented as a `nanmean`, so if one bucket contains zero valid observations, the average is NaN anyway.

I like your idea to be able to switch between `mean` and `nanmean`. And I'd vote for introducing a new kwarg for this. Xarray calls it `skipna` ([example](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.mean.html)), which is very intuitive I think.

**Comment by ameraner** [comment]
Thanks @sfinkens for your feedback, `skipna` is a good idea! I'll go for eliminating `mask_all_nan` and introduce `skipna` then, if @pnuu has no contrary opinion.

**Comment by pnuu** [comment]
Sounds good to me. I'm not sure what I've been thinking when implementing the `mask_all_nan` kwarg. Probably not much :roll_eyes:

**Comment by ameraner** [comment]
@sfinkens @pnuu thanks for your feedback. Another thing that I just noticed: if the input data array is of integer type, masked data will probably have a defined (very big or negative) integer FillValue. This masked data would be handled as valid by the bucket resampler, messing with the average computation. Moreover, the returned averaged array will be `float64`, no matter what the input type is.

What do you think about adding something like
```python
# at beginning of method

data = da.where(data == fill_value, np.nan, data)

# rest of method

return average.astype(data.dtype)
```
This would handle the FillValues as non-valid, therefore not interfering with the other averaging operations.

For your convenience, this is a link to the current method: https://github.com/pytroll/pyresample/blob/master/pyresample/bucket/__init__.py#L202-L226

**Comment by sfinkens** [comment]
Do you have a specific use case in mind where you would want the average to be an integer? I can imagine that in the majority of cases users would want the average of an integer data field to be a float. For example when averaging a binary cloud mask users probably expect the method to return a cloud fraction between 0 and 1.

Regarding the fill value: Sounds good to me!

**Comment by ameraner** [comment]
Yeah, I was thinking about downsampling a binary mask to another binary mask. But yes, it's a bad idea and a counter-intuitive behavior to hardcode the casting in the resampler! One can always do it manually on the returned value, if whished.
So I'll just go for the fill_value replacing!
