### ISSUE TITLE
Wrong formula used for the full width at half maximum

### ISSUE THREAD

**Issue by johnlavelle** [pytroll/pyresample#33]
In pyresample/utils.py, the formula in the function `fwhm2sigma()` is as follow:
`fwhm / (2 * np.sqrt(np.log(2)))`.
However, it should be: 
`fwhm / (2 * np.sqrt(2 * np.log(2)))`,
according to [Mathworld: Gaussian Function](http://mathworld.wolfram.com/GaussianFunction.html) Equation 8.

**Comment by storpipfugl** [comment]
It's acutally the gaussian applied by the gaussian resample that's wrong: exp(-dist^2/sigma_k^2). To not break numerical backwards compatibility fwhm2sigma was provided as a converter from real gaussian parameter to pyresample "sigma"

**Comment by Harshitjayaswal** [comment]
@storpipfugl I need to contact you with regard to your pyhandy model,could you please provide me with your contact details?

**Comment by Harshitjayaswal** [comment]
if you don't want to publicly post it please email me at harshitjayaswal@utexas.edu

**Comment by mraspaud** [comment]
Can we close this issue ?
