### ISSUE TITLE
Deprecated numpy data types (numpy >=1.20.0)

### ISSUE THREAD

**Issue by danschef** [pytroll/pyresample#345]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
.../lib/python3.9/site-packages/pyresample/kd_tree.py:459: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  valid_output_index = valid_output_index.astype(np.bool)

```
#### Problem description

The data types  numpy.bool, numpy.int, np.float, np.object, ...  are deprecated in numpy 1.20 and need to be replaced by the builtin types. The above warning is just an example but I guess, these data types have to be replaced at many positions in pyresample.

**Comment by djhoese** [comment]
Thanks for filing the issue. I was aware that these were happening, but thought I had fixed them all. What version of pyresample are you using?

**Comment by djhoese** [comment]
Yep, that particular line should be fixed in the latest pyresample release (1.18.0):

https://github.com/pytroll/pyresample/blob/9801978eb9f64d78b092cf2bd73f387e6edda9ca/pyresample/kd_tree.py#L460

**Comment by djhoese** [comment]
If you're experiencing this issue for other bits of pyresample, please let me know and feel to comment here.

**Comment by danschef** [comment]
Ahh, you are right, I still have 1.16 installed. Then, it´s my fault, sorry.

**Comment by djhoese** [comment]
No problem. Thanks for lettings us know even if it was something we already knew about :stuck_out_tongue_winking_eye:

**Comment by danschef** [comment]
Yes, I simply forgot that I pinned pyresample to <1.17 due to an incompatibility with between my own package and pyresample 1.17, somehow related to #325.
