### ISSUE TITLE
Handle X/Y in meters for CF conversion

### ISSUE THREAD

**Issue by djhoese** [pytroll/pyresample#355]
#### Problem description

This was brought up on slack when working with Satpy's `cf` writer and then trying to read it back. The `cf` writer uses `AreaDefinition.crs.to_cf` [here](https://github.com/pytroll/satpy/blob/153d8685699f546e6a4f91d06a2327b8efed651d/satpy/writers/cf_writer.py#L154) to convert the CRS information to a grid_mapping variable. I'm not really sure where the x/y variables are handled. If a user then tries to read that NetCDF file back and get the area using `AreaDefinition.from_cf` they get the wrong units from the extent because `_convert_XY_CF_to_Proj` assumes that geostationary projections are in radians, but they can also be in microradians or meters. It also isn't clear to me why it sets the `units` to `None` when the comment above it says it is meters. Shouldn't it just be explicit and set it to meters?

https://github.com/pytroll/pyresample/blob/91b8ba79461af9ec15081e94b43ec4d82b4a3141/pyresample/utils/cf.py#L64-L77

Sorry, I don't have a code example right now. Note that at the time of writing the CF reader in Satpy doesn't read AreaDefinitions, but it should in the future.

**Comment by zxdawn** [comment]
So, for the goes projection, the possible wrong parameters are 'first', 'last', 'spacing', right?

**Comment by djhoese** [comment]
Side request for this issue: Replace the `to_dict` usage with a check like this for checking if it is geostationary: https://github.com/pytroll/pyresample/blob/645bcdca9021dfd171564a18560a2c5e9389533f/pyresample/geometry.py#L1273-L1276

I think the `if` statement in the above mentioned method just needs to be updated to say `if crs_dict['proj'] == 'geos' and crs_dict.get('units', 'radians') == 'radians':`. There should be a way to access the units directly from the CRS object but I don't remember the series of attributes off the top of my head. Or maybe `axis_info.get('units', 'radians')` could just be used? I think I've also seen these defined as `microradians` but lets ignore that for now.

I also don't think the units in the axis_info should be set to None, I think they should be explicitly set to radians inside this if statement.

**Comment by djhoese** [comment]
Was just looking at an ABI L1b file, they use 'rads' for the units. Not sure that is CF/udunits compliant but it still exists so that should probably be handled too.

**Comment by zxdawn** [comment]
The output of `units` in the `axis_info` dict is 'm' for ABI L1b file. Where did you check it is 'rads'?

**Comment by djhoese** [comment]
In an old l1b file, not one generated by satpy.

**Comment by zxdawn** [comment]
This one works well for AWS ABI L1b file:

```
def _convert_XY_CF_to_Proj(crs, axis_info):
    """Convert XY values from CF to PROJ convention. With CF =< 1.9 only affects geostrationary projection."""
    crs_dict = crs.to_dict()

    if crs_dict['proj'] == 'geos' and crs_dict.get('units', 'radians') in ['radians', 'rads']:
        satellite_height = crs_dict['h']
        for k in ('first', 'last', 'spacing'):
            axis_info[k] *= satellite_height
        axis_info['units'] = axis_info.get('units', 'radians')
```

**Comment by djhoese** [comment]
The default inside the `if` should be `meters` not `radians`, but otherwise that looks good. PR?
