### ISSUE TITLE
`get_proj_coords` result of Satpy is different from that of `load_cf_area`

### ISSUE THREAD

**Issue by zxdawn** [pytroll/pyresample#365]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
import xarray as xr
from glob import glob
from satpy import Scene
from pyresample.utils import load_cf_area

abi_dir = '../data/GOES-16/ABI_L1/'
abi_name = 'OR_ABI-L1b-RadC-M6C13_G16_s'
channel = 'C13'
reader = 'abi_l1b'

filenames = glob(abi_dir+abi_name+'2020153000*')
scn = Scene([filenames[0]], reader='abi_l1b')
scn.load(['C13'])

# satpy method
x,y = scn['C13'].area.get_proj_coords()

# pyresample method
abi_area_test, cf_info_test = load_cf_area(filenames[0])
x_cf, y_cf = abi_area_test.get_proj_coords()
```
#### Problem description
Even though #362 is fixed, the `x` is different with `x_cf`.
Here's the plot of `xr.DataArray(x-x_cf).plot()`:
![image](https://user-images.githubusercontent.com/30388627/120131917-f4074000-c1fb-11eb-9111-2644d42f1382.png)

#### Expected Output
They are the same.

**Comment by zxdawn** [comment]
As this is quite small compared with 10^6, I suppose this is caused by the floating accuracy error ...

**Comment by djhoese** [comment]
So if you look at the `abi_l1b` (or maybe abi_base) reader code you'll see I did **a lot** of work getting the projection coordinates to be very exact to their theoretical/ideal values. The main issue is that in the L1b files the coordinate scale factors are stored as 32-bit floats, but this is not precise enough for the size/value of the coordinate values. If you do a "naive" multiply on the coordinates with the scale_factor (as you **should** be able to do) your coordinate values will slowly get further and further from what they should be. Each pixel should be the same size, but if you compare the unscaled X and Y values (after the scale factor and add_offset have been applied) you'll see that they really aren't.

**Comment by djhoese** [comment]
Here's the code of interest:

https://github.com/pytroll/satpy/blob/1289aa3e4fc454fcc63028cc99161effcfbccb32/satpy/readers/abi_base.py#L236-L246

You'll see `h` is defined/converted to 64-bit float and that I round the `h * val` to 6 decimal places to avoid precision issues.

**Comment by djhoese** [comment]
I should have maybe been more clear: For the abi_l1b reader this amount of difference is expected in my opinion. The work done in the abi_l1b reader was to correct/workaround an issue with the format/specification of the L1b format. So the regular `load_cf_area` isn't incorrect with the values it is producing, but it isn't accurate for what the files are actually supposed to be representing. It isn't pyresample's (or satpy's) fault.
