### ISSUE TITLE
Importing pyresample without having Xarray and/or zarray raises UserWarning

### ISSUE THREAD

**Issue by geoffrey464** [pytroll/pyresample#375]
#### Code Sample, a minimal, complete, and verifiable piece of code

```python
import pyresample
```
```
test_resample_import.py:10: UserWarning: XArray and/or zarr not found, XArrayBilinearResampler won't be available.
  warnings.warn("XArray and/or zarr not found, XArrayBilinearResampler won't be available.")
```

#### Problem description

When importing pyresample without having XArray installed the above warning is thrown. I consciously have not installed XArray with this package since it is not on a major version yet. However this means that every time I run the pyresample import for my code I see this warning at the top of the stdout. If pyresample requires XArray to be importable should Xarray be included as a dependency (I noticed that it is included on the "xarray_bilinear" extras)?

A possible solution to this without requiring XArray as a dependency would be to include the ImportWarning category on the try/except block in the pyresample/bilinear/__init__.py file.
```
    warnings.warn("XArray and/or zarr not found, XArrayBilinearResampler won't be available.", category=ImportWarning)
```
This would still log the warning but only display it in Python Development Mode.

I think that there should be error handling when the user tries to use the XArrayBilinearResampler without having Xarray installed, but not on the import of the package. Since it is still unknown at import if the user will be using XArrayBilinearResampler or just NumpyBilinearResampler. 

I currently have a hotfix by surrounding the import statment with a catch_warnings() block,
```
with warnings.catch_warnings():
    warnings.simplefilter('ignore', UserWarning)
    import pyresample
```

#### Versions of Python, package at hand and relevant dependencies
I am currently testing this on python 3.8 with the current base requirements: setuptools>=3.2', 'pyproj>=2.2', 'configobj','pykdtree>=1.3.1', 'pyyaml', 'numpy>=1.10.0',

Thanks for your consideration!

**Comment by djhoese** [comment]
Thanks for filing this. Xarray should not be a hard requirement (at least not right now) as there are a lot of features in pyresample that don't require it. You method of a workaround is the best thing for right now. I like the idea of adding the ImportWarning (what is Python Development Mode). @pnuu what do you think about that?

> I consciously have not installed XArray with this package since it is not on a major version yet.

In the scientific python world this may not get you very far. Xarray is a major asset to the scientific python community and if you have a chance to use it I would highly recommend it. Especially when combined with `dask` (another dependency that pyresample could use but shouldn't have a hard requirement on right now).

Lastly, a lot of this stuff may get automatically cleaned up when we move to [Pyresample 2.0](https://github.com/pytroll/pyresample/milestone/3).

**Comment by geoffrey464** [comment]
Some other information regarding the [ImportWarning](https://docs.python.org/3/library/exceptions.html#ImportWarning) and the [Python Development Mode ](https://docs.python.org/3/library/devmode.html#devmode) (essentially running python with a -X flag).

Understood about Xarray, it seems to be well supported. I just wanted to post this issue and workaround for others who may have run into the warning. Looking forward to 2.0!
