### ISSUE TITLE
Versions from 1.2.0 fail to build on Windows.

### ISSUE THREAD

**Issue by cpaulik** [pytroll/pyresample#39]
I'm no expert on Windows compilation but noticed in CI that pyresample fails to build for versions greater than 1.1.6.

See [here](https://ci.appveyor.com/project/cpaulik/pytesmo/build/1.0.385/job/0ja9fp777oderewf) for a successful build and [here](https://ci.appveyor.com/project/cpaulik/pytesmo/build/1.0.381/job/y6qpsnjc9bsw5mcj) for a broken one. 

You might want to consider using Appveyor to test your software on Windows if you want to support it.

**Comment by mraspaud** [comment]
@cpaulik thanks for reporting the issue!
We introduced a small C library in 1.2.0 for the new Elliptical Weighted Average feature, and indeed tested only on Mac and Linux.

I have unfortunately no access to windows machines, so it might be a bit hard to debug, although I suspect the extra compile arguments are compatible with gcc:
`extra_compile_args=["-O3", "-Wno-unused-function"]`

Can you try to remove these to see how it behaves ?

Regarding Appveyor, it sounds like a good idea. Do you have any experience with it ? Would you like helping set up pyresample in it ?

**Comment by davidh-ssec** [comment]
This should be fixed now based on work discussed on #40.
