### ISSUE TITLE
Release GIL in gradient search resampling

### ISSUE THREAD

**Issue by djhoese** [pytroll/pyresample#445]
#### Problem description

It was noted in recent EWA profiling that the Python Global Interpreter Lock (GIL) was not being released during processing which caused CPU usage to hover around 100% even though multiple dask workers were being used. Adding `with nogil:` to the proper spots in the Cython code improved execution time and increased CPU usage to ~700% usage for 8 workers. This same lack of releasing the GIL was noticed in the gradient search code. Specifically here:

https://github.com/pytroll/pyresample/blob/c930465a94f63c9d6a9db1b0c3db033d0369a396/pyresample/gradient/_gradient_search.pyx#L124-L133

and here:

https://github.com/pytroll/pyresample/blob/c930465a94f63c9d6a9db1b0c3db033d0369a396/pyresample/gradient/_gradient_search.pyx#L240-L248

My initial tests at naively adding `with nogil:` around these calls resulted in a segmentation fault. My hope is that someone like @mraspaud who is familiar with the algorithm can figure out why this might be happening.

**Comment by mraspaud** [comment]
For reference: I looked a this last week and was unable to pinpoint where the segfault was coming from. Cygdb wasn't very cooperative.
