### ISSUE TITLE
Conda package and the use of the IOOS channel in the CI

### ISSUE THREAD

**Issue by ocefpaf** [pytroll/pyresample#45]
Hi there, I am the maintainer of the IOOS channel and I noticed that `pyresample` is [using](https://github.com/pytroll/pyresample/blob/master/appveyor.yml#L64) that channel to get `basemap` on Windows. Note that the IOOS channel is now deprecated and our efforts are to maintain a better `basemap` recipe in the conda-forge channel. See https://github.com/conda-forge/basemap-feedstock and https://github.com/conda-forge/basemap-data-hires-feedstock

PS: I also created conda packages for `pyresample` [here](https://github.com/conda-forge/pyresample-feedstock). Anyone interested in becoming a maintainer there is welcome to send a PR adding their GitHub handles to the [maintainers list](https://github.com/conda-forge/pyresample-feedstock/blob/master/recipe/meta.yaml#L42-L44).

**Comment by davidh-ssec** [comment]
So I should be able to do `conda install -c conda-forge basemap` as a replacement for our current IOOS stuff?

**Comment by ocefpaf** [comment]
Almost :grimacing: `conda install -c conda-forge basemap` will get you the `basemap` core. By core I mean a workng `basemap` module with minimum bundled data. If you do: `conda install -c conda-forge basemap-data-hires`, which depends on the core `basemap` BTW, will get you the high resolution data and `basemap` in one go.

In `conda-forge` chose to break from the previous recipes b/c most CIs want to download just the core of `basemap` for a the tests while only  (some) end users want all the high resolution data.

**Comment by davidh-ssec** [comment]
Thanks I'll try it out.

**Comment by davidh-ssec** [comment]
I just remembered this issue existed. From what I remember and from what I can tell this has all been resolved. There are a couple commits in `pre-master` that aren't included with the 1.2.5 version on conda-forge, but they are all to fix CI tests it seems. Unless there is an objection I'll close this issue.

**Comment by ocefpaf** [comment]
The line I mentioned above still exists: https://github.com/pytroll/pyresample/blob/master/appveyor.yml#L64

**Comment by davidh-ssec** [comment]
Yes but only in master, it is fixed in pre-master. That's why I wasn't sure if a new release was really needed since it only affects CI. @mraspaud how do you feel about a new release? Are there other PRs that you wanted to pull in?

**Comment by ocefpaf** [comment]
> Yes but only in master, it is fixed in pre-master. 

Got. That is quite an unusual setup. Most people will think that `master` is the latest dev version.

**Comment by davidh-ssec** [comment]
Well `pre-master` is the dev/unstable version and master is the release/stable version. I wouldn't say it is unusual since it follows the popular model of persistent `master` and `develop` branches and additional feature/bugfix branches as needed. The unusual part is that we've had these commits sitting in `pre-master` for so long when they are needed for passing on some of the CIs.
