### ISSUE TITLE
Can not install on Centos 7

### ISSUE THREAD

**Issue by meersonv** [pytroll/pyresample#53]
I try to install on last Centos version and receive the following message:
"RuntimeError: maximum recursion depth exceeded in cmp" 

See full output of install in the file attached
[pyresamle_install_error.txt](https://github.com/pytroll/pyresample/files/738184/pyresamle_install_error.txt)

Thank you.

**Comment by meersonv** [comment]
Of course, the problem is not in "RuntimeError: maximum recursion depth exceeded in cmp" message, but in some error in the installation process.

**Comment by mraspaud** [comment]
Hi,
I'm not sure this is directly a pyresample issue, since it seems to happen when setuptools is getting update. What happens if you just run
`pip install --upgrade setuptools` ?

**Comment by meersonv** [comment]
Thank you, it was the problem.
