### ISSUE TITLE
ImportError: undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by mitkin** [pytroll/pyresample#85]
Filing an issue for information for reference:

I experienced an error when importing `fornav` and `ll2cr`:

```python
    importError: /home/mikhail/.virtualenvs/def27/local/lib/python2.7/site-packages/pyresample/ewa/_ll2cr.so: undefined symbol: PyFPE_jbuf
```
Apparently this is caused by two incompatible versions of numpy installed, one in virtualenv and another as a system package `python-numpy`. Obviously the virtualenv was not totally isolated from system site-packages.

**Comment by mraspaud** [comment]
Thanks for reporting this.

@davidh-ssec Do you see anything we can do about this ? Otherwise I propose we close the issue.

**Comment by davidh-ssec** [comment]
No there is nothing we can do about this. This all happens after pyresample is downloaded on the machine and it is compiling the (completely valid) C code. If it compiles with one of the numpys=bad, if it compiles with the other=good.
