### ISSUE TITLE
ImageContainerQuick does not mask fill values in high resolution images

### ISSUE THREAD

**Issue by Funkensieper** [pytroll/pyresample#87]
``ImageContainerQuick.resample()`` does not mask fill values in high resolution images. The output is a masked array, but its mask is ``False``. It works fine with low resolutions though. The problem seems to be independent of the projection (I didn't check all). 

I'm using pyresample-1.5.0 with numpy-1.13.0 .

Example:

    import numpy as np
    import pyresample.geometry
    import pyresample.image
    import pyresample.plot
    import matplotlib.pyplot as plt
    from pycmsaf.geometry import get_proj_corners
    
    for nx, ny in zip([360, 3600], [180, 1800]):
        # Generate some test data with masked elements
        x = np.arange(nx, dtype='f4')
        y = np.arange(ny, dtype='f4')
        x *= 2 * np.pi / x.max()
        y *= 2 * np.pi / y.max()
        mx, my = np.meshgrid(x, y)
        data = np.sin(np.sqrt(mx ** 2 + my ** 2))
        data = np.ma.masked_where(data > 0.98, data)
    
        # Define regular lon-lat grid (lower left corner: [-180, -90], upper right
        # corner: [180, 90])
        regular_grid = pyresample.geometry.AreaDefinition(
            area_id='my_regular_grid',
            name='Regular 1x1 degree grid',
            proj_id='my_id',
            proj_dict={'proj': 'eqc', 'lon_0': 0},
            x_size=nx,
            y_size=ny,
            area_extent=[-20037508.342789244, -10018754.171394622,
                         20037508.342789244, 10018754.171394622])
    
        # Define web-mercator grid (lower left corner: [-180, -85], upper right
        # corner: [180, 85])
        proj4_str = '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 ' \
                    '+x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null'
        web_mercator = pyresample.utils.get_area_def(
            area_id='my_web_mercator',
            area_name='Web Mercator',
            proj_id='my_id',
            proj4_args=proj4_str,
            x_size=ny,
            y_size=ny,
            area_extent=[-20037508.342789244, -19971868.88040857,
                         20037508.342789244, 19971868.880408563]
        )
    
        # Resample data from regular lon-lat grid to web-mercator grid
        con_reg = pyresample.image.ImageContainerQuick(
            image_data=data, geo_def=regular_grid, fill_value=None)
        con_merc = con_reg.resample(web_mercator)
        data_merc = con_merc.image_data
        print data_merc.mask
    
        # Plot data
        fig, ax = plt.subplots()
        bmap = pyresample.plot.area_def2basemap(web_mercator, resolution='c')
        bmap.ax = ax
        bmap.drawcoastlines()
        bmap.imshow(data_merc, origin='upper')
        ax.set_title('nx={0}, ny={1}'.format(nx, ny))
    
    plt.show()

Output:

![lo](https://user-images.githubusercontent.com/1991007/34210313-bc3f7c3c-e595-11e7-9518-b612e4237668.png)
![hi](https://user-images.githubusercontent.com/1991007/34210312-bc20bd9c-e595-11e7-9efd-2fbb15819a98.png)

**Comment by davidh-ssec** [comment]
So you are saying in the first iteration of the loop there are no masked values, in the second iteration (the lower resolution) there are masked values?

**Comment by Funkensieper** [comment]
In the first iteration (the lower resolution) there are masked values, but in the second iteration (the higher resolution) there are no masked values. I have attached two images to make it more clear.

**Comment by davidh-ssec** [comment]
Were those generated from the same code above? The nx/ny numbers are different.

**Comment by Funkensieper** [comment]
Yes. First iteration (nx, ny) = (360, 180), second iteration (nx, ny) = (3600, 1800).

**Comment by davidh-ssec** [comment]
Oh sorry, missed the zip.

**Comment by Funkensieper** [comment]
With ImageContainerNearest the masks are correct.
