### ISSUE TITLE
Packaging a .egg-info with pyresample?

### ISSUE THREAD

**Issue by mraspaud** [pytroll/pyresample#9]
_From [lavergne...@gmail.com](https://code.google.com/u/110388910077036912843/) on May 06, 2013 08:33:05_

Hi,

This is more a question than a defect. When I "python setup.py install" other modules than pyresample, it is not rare to obtain a ".egg-info" file installed under site-packages/. This is not the case for pyresample:

Here is an example from a software we have been developing and that builds several packages from source:
<kapphorn|pmw_decode> =:D ls mypython/lib/python2.6/site-packages/*.egg-info
mypython/lib/python2.6/site-packages/basemap-1.0-py2.6.egg-info
mypython/lib/python2.6/site-packages/bufr_metadb-0.1-py2.6.egg-info
mypython/lib/python2.6/site-packages/bufr_transform-0.1-py2.6.egg-info
mypython/lib/python2.6/site-packages/lockfile-0.9.1-py2.6.egg-info
mypython/lib/python2.6/site-packages/netCDF4-0.9.1-py2.6.egg-info
mypython/lib/python2.6/site-packages/python_bufr-0.2_3-py2.6.egg-info
mypython/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg-info
mypython/lib/python2.6/site-packages/sqlalchemy_marshall-1.0-py2.6.egg-info
mypython/lib/python2.6/site-packages/xml_marshall-1.0-py2.6.egg-info

BUT:
ls mypython/lib/python2.6/site-packages/pyresample-0.7.7-py2.6.egg-info
no such file or directory.

So I wonder if this is common practice to have this .egg-info installed and why does not appear for pyresample?

I use the .egg-info as a target for my Makefile rules: if the .egg-info is newer than the tar-ball containing the source code, do not "python setup.py install". And I cannot apply the same trick for pyresample.

Thomas

_Original issue: http://code.google.com/p/pyresample/issues/detail?id=9_

**Comment by davidh-ssec** [comment]
I don't think this is an issue any longer. If you install from a source distribution (`python setup.py sdist` to create; `pip install pyresample-1.5.0.tar.gz` to install) you get an `egg-info` directory. If you install from a wheel (`python setup.py bdist_wheel` to create; `pip install pyresample-1.5.0-cp27-none-macosx_10_12_x86_64.whl` to install) you will get a `dist-info` directory.

If this is still an issue for you we can reopen this.
